[book]
title = "Sõber Documentation"
authors = ["Sõber Contributors"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "build"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/sober-io/sober"
edit-url-template = "https://github.com/sober-io/sober/edit/main/docs/book/{path}"
