{
 "title": "Database",
 "tags": [
  "sober",
  "generated",
  "sober-db"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active (in-use + idle) connections in the pool",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sober_pg_pool_connections_active)",
     "legendFormat": "Active (in-use + idle) connections in the pool"
    }
   ]
  },
  {
   "title": "Active (in-use + idle) connections in the pool (over time)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sober_pg_pool_connections_active)",
     "legendFormat": "Active (in-use + idle) connections in the pool"
    }
   ]
  },
  {
   "title": "Idle connections in the pool",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sober_pg_pool_connections_idle)",
     "legendFormat": "Idle connections in the pool"
    }
   ]
  },
  {
   "title": "Idle connections in the pool (over time)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sober_pg_pool_connections_idle)",
     "legendFormat": "Idle connections in the pool"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total message content blocks stored",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sober_message_content_blocks_total[$__rate_interval]))",
     "legendFormat": "Total message content blocks stored"
    }
   ]
  }
 ]
}