apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    editable: false
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
        queries:
          - name: Request rate
            query: sum(rate(sober_api_request_total{$$__tags}[5m]))
          - name: Error rate
            query: sum(rate(sober_api_request_total{status=~"5..",$$__tags}[5m]))
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
