//! UUIDv7 newtype wrappers for domain entity identifiers.
//!
//! All IDs are time-ordered UUIDv7 values generated by the application.
//! The `define_id!` macro generates the boilerplate for each type.

use serde::{Deserialize, Serialize};
use std::fmt;
use uuid::Uuid;

/// Generates a newtype wrapper around [`Uuid`] with standard trait
/// implementations.
///
/// Each generated type provides:
/// - `new()` — generates a fresh UUIDv7
/// - `from_uuid(uuid)` — wraps an existing UUID
/// - `as_uuid()` — borrows the inner UUID
/// - `Display` — delegates to the inner UUID
///
/// Derives: `Debug`, `Clone`, `Copy`, `PartialEq`, `Eq`, `Hash`,
/// `Serialize`, `Deserialize`. When the `postgres` feature is enabled,
/// also derives `sqlx::Type` with transparent representation.
macro_rules! define_id {
    ($(#[doc = $doc:expr])* $name:ident) => {
        $(#[doc = $doc])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, Hash,
            Serialize, Deserialize,
        )]
        #[cfg_attr(feature = "postgres", derive(sqlx::Type))]
        #[cfg_attr(feature = "postgres", sqlx(transparent))]
        pub struct $name(Uuid);

        impl $name {
            /// Generates a new time-ordered UUIDv7 identifier.
            #[must_use]
            pub fn new() -> Self {
                Self(Uuid::now_v7())
            }

            /// Wraps an existing [`Uuid`] value.
            #[must_use]
            pub fn from_uuid(uuid: Uuid) -> Self {
                Self(uuid)
            }

            /// Returns a reference to the inner [`Uuid`].
            #[must_use]
            pub fn as_uuid(&self) -> &Uuid {
                &self.0
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                self.0.fmt(f)
            }
        }
    };
}

define_id!(
    /// Unique identifier for a user account.
    UserId
);

define_id!(
    /// Unique identifier for a memory/authorization scope.
    ScopeId
);

impl ScopeId {
    /// The global (system-wide) scope, used when a scope is not user- or
    /// group-specific (e.g. default role assignments).
    pub const GLOBAL: Self = Self(Uuid::nil());
}

define_id!(
    /// Unique identifier for a conversation.
    ConversationId
);

define_id!(
    /// Unique identifier for a message within a conversation.
    MessageId
);

define_id!(
    /// Unique identifier for an active user session.
    SessionId
);

define_id!(
    /// Unique identifier for an authorization role.
    RoleId
);

define_id!(
    /// Unique identifier for a workspace.
    WorkspaceId
);

define_id!(
    /// Unique identifier for a scheduled job.
    JobId
);

define_id!(
    /// Unique identifier for a single job execution run.
    JobRunId
);

define_id!(
    /// Unique identifier for a git repository registered in a workspace.
    WorkspaceRepoId
);

define_id!(
    /// Unique identifier for a git worktree.
    WorktreeId
);

define_id!(
    /// Unique identifier for a workspace artifact.
    ArtifactId
);

define_id!(
    /// Unique identifier for an audit log entry.
    AuditLogId
);

define_id!(
    /// Unique identifier for a stored encrypted secret.
    SecretId
);

define_id!(
    /// Unique identifier for a stored encryption key (DEK).
    EncryptionKeyId
);

define_id!(
    /// Unique identifier for a user-created tag.
    TagId
);

define_id!(
    /// Unique identifier for a registered plugin.
    PluginId
);

/// Unique identifier for a tool (string-based, not UUID).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ToolId(String);

impl ToolId {
    /// Creates a new tool identifier from a string.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// Returns the tool identifier as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ToolId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_ids_are_distinct() {
        let a = UserId::new();
        let b = UserId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn display_matches_uuid_format() {
        let id = UserId::new();
        let displayed = id.to_string();
        // UUIDs are 36 chars: 8-4-4-4-12
        assert_eq!(displayed.len(), 36);
        assert!(Uuid::parse_str(&displayed).is_ok());
    }

    #[test]
    fn from_uuid_roundtrip() {
        let uuid = Uuid::now_v7();
        let id = ScopeId::from_uuid(uuid);
        assert_eq!(*id.as_uuid(), uuid);
    }

    #[test]
    fn serde_roundtrip() {
        let id = MessageId::new();
        let json = serde_json::to_string(&id).unwrap();
        let deserialized: MessageId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, deserialized);
    }

    #[test]
    fn tool_id_display() {
        let id = ToolId::new("web_search");
        assert_eq!(id.as_str(), "web_search");
        assert_eq!(id.to_string(), "web_search");
    }
}
